### ISSUE TITLE
Compilation error after updating heaps.

### ISSUE THREAD

**Issue by qlambert-pro** [HeapsIO/heaps#997]
After updating heaps from v1.8.0 to v1.9.1, my project which uses domkit triggers compilation errors:

> /usr/share/haxe/lib/heaps/1,9,1/h2d/domkit/BaseComponents.hx:10: characters 17-34 : Unknown identifier : parseFloatPercent
> /usr/share/haxe/lib/heaps/1,9,1/h2d/domkit/InitComponents.hx:9: characters 21-38 : Class<domkit.Macros> has no field defaultParserPath

Is there a workaround? Reverting heaps to 1.8.0 triggers other compilation errors, so it does not seem to be an option.
